version: "3.8"
services:
  rate-limiter-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "rate-limiter-server"
    ports:
      - "8080:8080"
    volumes:
      - ./:/app